plugins:
  - jekyll-redirect-from
  - jekyll-github-metadata
  
theme: jekyll-theme-cayman
title: QMPY Toolkits
github:
  repository_url: https://github.com/wolverton-research-group
  
highlighter: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter_opts:
    disable: true

include:
  static
